#!/bin/sh

echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 223.5.5.5" >> /etc/resolv.conf
echo "nameserver 119.29.29.29" >> /etc/resolv.conf

uci set turboacc.config.fullcone_nat='0'
uci commit turboacc

/etc/init.d/ restart

exit 0
