#!/bin/sh

echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 223.5.5.5" >> /etc/resolv.conf
echo "nameserver 119.29.29.29" >> /etc/resolv.conf

model=$(cat /tmp/sysinfo/model)
case $model in 
	M21*)
		uci set turboacc.config.fullcone_nat='0'
        uci commit turboacc
        /etc/init.d/turboacc restart
        echo "close turboacc"
	;;
	*)
		echo "open turboacc"
	;;
esac

#change luci port, compat OUI
uci del_list uhttpd.main.listen_http='0.0.0.0:80'
uci del_list uhttpd.main.listen_http='[::]:80'
uci del_list uhttpd.main.listen_https='0.0.0.0:443'
uci del_list uhttpd.main.listen_https='[::]:443'
uci add_list uhttpd.main.listen_http='0.0.0.0:8080'
uci add_list uhttpd.main.listen_http='[::]:8080'
uci add_list uhttpd.main.listen_https='0.0.0.0:4433'
uci add_list uhttpd.main.listen_https='[::]:4433'
uci commit uhttpd
/etc/init.d/uhttpd restart



exit 0
