#!/bin/sh

echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 223.5.5.5" >> /etc/resolv.conf
echo "nameserver 119.29.29.29" >> /etc/resolv.conf


echo "*/1 * * * * /sbin/ylx_ModemState_Detect.sh" | crontab -

exit 0